version: '3'

services:
  payment-management-service:
    build:
      context: ./PaymentManagementService
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    depends_on:
      - mongo

  client-service:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
