apiVersion: v1
kind: Service
metadata:
  name: course-management-service
spec:
  selector:
    app: course-management-service
  ports:
  - protocol: TCP
    port: 3002
    targetPort: 3002
  type: ClusterIP
