apiVersion: v1
kind: Service
metadata:
  name: enrollment-management-service
spec:
  selector:
    app: enrollment-management-service
  ports:
  - protocol: TCP
    port: 3004
    targetPort: 3004
  type: ClusterIP
