apiVersion: v1
kind: Service
metadata:
  name: payment-management-service
spec:
  selector:
    app: payment-management-service
  ports:
  - protocol: TCP
    port: 3003
    targetPort: 3003
  type: ClusterIP
